//! Achievement dependency and display facts observed from MCP919.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct AchievementDefinition {
    pub id: &'static str,
    pub parent: Option<&'static str>,
    pub column: i32,
    pub row: i32,
    pub item_id: i16,
    pub damage: i16,
    pub special: bool,
}

pub const ACHIEVEMENTS: &[AchievementDefinition] = &[
    AchievementDefinition {
        id: "achievement.openInventory",
        parent: None,
        column: 0,
        row: 0,
        item_id: 340,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.mineWood",
        parent: Some("achievement.openInventory"),
        column: 2,
        row: 1,
        item_id: 17,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.buildWorkBench",
        parent: Some("achievement.mineWood"),
        column: 4,
        row: -1,
        item_id: 58,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.buildPickaxe",
        parent: Some("achievement.buildWorkBench"),
        column: 4,
        row: 2,
        item_id: 270,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.buildFurnace",
        parent: Some("achievement.buildPickaxe"),
        column: 3,
        row: 4,
        item_id: 61,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.acquireIron",
        parent: Some("achievement.buildFurnace"),
        column: 1,
        row: 4,
        item_id: 265,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.buildHoe",
        parent: Some("achievement.buildWorkBench"),
        column: 2,
        row: -3,
        item_id: 290,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.makeBread",
        parent: Some("achievement.buildHoe"),
        column: -1,
        row: -3,
        item_id: 297,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.bakeCake",
        parent: Some("achievement.buildHoe"),
        column: 0,
        row: -5,
        item_id: 354,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.buildBetterPickaxe",
        parent: Some("achievement.buildPickaxe"),
        column: 6,
        row: 2,
        item_id: 274,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.cookFish",
        parent: Some("achievement.buildFurnace"),
        column: 2,
        row: 6,
        item_id: 350,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.onARail",
        parent: Some("achievement.acquireIron"),
        column: 2,
        row: 3,
        item_id: 66,
        damage: 0,
        special: true,
    },
    AchievementDefinition {
        id: "achievement.buildSword",
        parent: Some("achievement.buildWorkBench"),
        column: 6,
        row: -1,
        item_id: 268,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.killEnemy",
        parent: Some("achievement.buildSword"),
        column: 8,
        row: -1,
        item_id: 352,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.killCow",
        parent: Some("achievement.buildSword"),
        column: 7,
        row: -3,
        item_id: 334,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.flyPig",
        parent: Some("achievement.killCow"),
        column: 9,
        row: -3,
        item_id: 329,
        damage: 0,
        special: true,
    },
    AchievementDefinition {
        id: "achievement.snipeSkeleton",
        parent: Some("achievement.killEnemy"),
        column: 7,
        row: 0,
        item_id: 261,
        damage: 0,
        special: true,
    },
    AchievementDefinition {
        id: "achievement.diamonds",
        parent: Some("achievement.acquireIron"),
        column: -1,
        row: 5,
        item_id: 56,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.diamondsToYou",
        parent: Some("achievement.diamonds"),
        column: -1,
        row: 2,
        item_id: 264,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.portal",
        parent: Some("achievement.diamonds"),
        column: -1,
        row: 7,
        item_id: 49,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.ghast",
        parent: Some("achievement.portal"),
        column: -4,
        row: 8,
        item_id: 370,
        damage: 0,
        special: true,
    },
    AchievementDefinition {
        id: "achievement.blazeRod",
        parent: Some("achievement.portal"),
        column: 0,
        row: 9,
        item_id: 369,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.potion",
        parent: Some("achievement.blazeRod"),
        column: 2,
        row: 8,
        item_id: 373,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.theEnd",
        parent: Some("achievement.blazeRod"),
        column: 3,
        row: 10,
        item_id: 381,
        damage: 0,
        special: true,
    },
    AchievementDefinition {
        id: "achievement.theEnd2",
        parent: Some("achievement.theEnd"),
        column: 4,
        row: 13,
        item_id: 122,
        damage: 0,
        special: true,
    },
    AchievementDefinition {
        id: "achievement.enchantments",
        parent: Some("achievement.diamonds"),
        column: -4,
        row: 4,
        item_id: 116,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.overkill",
        parent: Some("achievement.enchantments"),
        column: -4,
        row: 1,
        item_id: 276,
        damage: 0,
        special: true,
    },
    AchievementDefinition {
        id: "achievement.bookcase",
        parent: Some("achievement.enchantments"),
        column: -3,
        row: 6,
        item_id: 47,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.breedCow",
        parent: Some("achievement.killCow"),
        column: 7,
        row: -5,
        item_id: 296,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.spawnWither",
        parent: Some("achievement.theEnd2"),
        column: 7,
        row: 12,
        item_id: 397,
        damage: 1,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.killWither",
        parent: Some("achievement.spawnWither"),
        column: 7,
        row: 10,
        item_id: 399,
        damage: 0,
        special: false,
    },
    AchievementDefinition {
        id: "achievement.fullBeacon",
        parent: Some("achievement.killWither"),
        column: 7,
        row: 8,
        item_id: 138,
        damage: 0,
        special: true,
    },
    AchievementDefinition {
        id: "achievement.exploreAllBiomes",
        parent: Some("achievement.theEnd"),
        column: 4,
        row: 8,
        item_id: 313,
        damage: 0,
        special: true,
    },
    AchievementDefinition {
        id: "achievement.overpowered",
        parent: Some("achievement.buildBetterPickaxe"),
        column: 6,
        row: 4,
        item_id: 322,
        damage: 1,
        special: true,
    },
];

pub fn achievement(id: &str) -> Option<&'static AchievementDefinition> {
    ACHIEVEMENTS.iter().find(|definition| definition.id == id)
}
