//! Material predicate facts observed from the MCP919 block registry.
//! Each row is blocksMovement, isSolid, isIce, indexed by numeric block ID.
pub(crate) const MATERIAL_PROPERTIES: &[[bool; 3]] = &[
    [false, false, false], // 0
    [true, true, false],   // 1
    [true, true, false],   // 2
    [true, true, false],   // 3
    [true, true, false],   // 4
    [true, true, false],   // 5
    [false, false, false], // 6
    [true, true, false],   // 7
    [false, false, false], // 8
    [false, false, false], // 9
    [false, false, false], // 10
    [false, false, false], // 11
    [true, true, false],   // 12
    [true, true, false],   // 13
    [true, true, false],   // 14
    [true, true, false],   // 15
    [true, true, false],   // 16
    [true, true, false],   // 17
    [true, true, false],   // 18
    [true, true, false],   // 19
    [true, true, false],   // 20
    [true, true, false],   // 21
    [true, true, false],   // 22
    [true, true, false],   // 23
    [true, true, false],   // 24
    [true, true, false],   // 25
    [true, true, false],   // 26
    [false, false, false], // 27
    [false, false, false], // 28
    [true, true, false],   // 29
    [false, true, false],  // 30
    [false, false, false], // 31
    [false, false, false], // 32
    [true, true, false],   // 33
    [true, true, false],   // 34
    [true, true, false],   // 35
    [true, true, false],   // 36
    [false, false, false], // 37
    [false, false, false], // 38
    [false, false, false], // 39
    [false, false, false], // 40
    [true, true, false],   // 41
    [true, true, false],   // 42
    [true, true, false],   // 43
    [true, true, false],   // 44
    [true, true, false],   // 45
    [true, true, false],   // 46
    [true, true, false],   // 47
    [true, true, false],   // 48
    [true, true, false],   // 49
    [false, false, false], // 50
    [false, false, false], // 51
    [true, true, false],   // 52
    [true, true, false],   // 53
    [true, true, false],   // 54
    [false, false, false], // 55
    [true, true, false],   // 56
    [true, true, false],   // 57
    [true, true, false],   // 58
    [false, false, false], // 59
    [true, true, false],   // 60
    [true, true, false],   // 61
    [true, true, false],   // 62
    [true, true, false],   // 63
    [true, true, false],   // 64
    [false, false, false], // 65
    [false, false, false], // 66
    [true, true, false],   // 67
    [true, true, false],   // 68
    [false, false, false], // 69
    [true, true, false],   // 70
    [true, true, false],   // 71
    [true, true, false],   // 72
    [true, true, false],   // 73
    [true, true, false],   // 74
    [false, false, false], // 75
    [false, false, false], // 76
    [false, false, false], // 77
    [false, false, false], // 78
    [true, true, true],    // 79
    [true, true, false],   // 80
    [true, true, false],   // 81
    [true, true, false],   // 82
    [false, false, false], // 83
    [true, true, false],   // 84
    [true, true, false],   // 85
    [true, true, false],   // 86
    [true, true, false],   // 87
    [true, true, false],   // 88
    [true, true, false],   // 89
    [false, false, false], // 90
    [true, true, false],   // 91
    [true, true, false],   // 92
    [false, false, false], // 93
    [false, false, false], // 94
    [true, true, false],   // 95
    [true, true, false],   // 96
    [true, true, false],   // 97
    [true, true, false],   // 98
    [true, true, false],   // 99
    [true, true, false],   // 100
    [true, true, false],   // 101
    [true, true, false],   // 102
    [true, true, false],   // 103
    [false, false, false], // 104
    [false, false, false], // 105
    [false, false, false], // 106
    [true, true, false],   // 107
    [true, true, false],   // 108
    [true, true, false],   // 109
    [true, true, false],   // 110
    [false, false, false], // 111
    [true, true, false],   // 112
    [true, true, false],   // 113
    [true, true, false],   // 114
    [false, false, false], // 115
    [true, true, false],   // 116
    [true, true, false],   // 117
    [true, true, false],   // 118
    [false, false, false], // 119
    [true, true, false],   // 120
    [true, true, false],   // 121
    [true, true, false],   // 122
    [true, true, false],   // 123
    [true, true, false],   // 124
    [true, true, false],   // 125
    [true, true, false],   // 126
    [false, false, false], // 127
    [true, true, false],   // 128
    [true, true, false],   // 129
    [true, true, false],   // 130
    [false, false, false], // 131
    [false, false, false], // 132
    [true, true, false],   // 133
    [true, true, false],   // 134
    [true, true, false],   // 135
    [true, true, false],   // 136
    [true, true, false],   // 137
    [true, true, false],   // 138
    [true, true, false],   // 139
    [false, false, false], // 140
    [false, false, false], // 141
    [false, false, false], // 142
    [false, false, false], // 143
    [false, false, false], // 144
    [true, true, false],   // 145
    [true, true, false],   // 146
    [true, true, false],   // 147
    [true, true, false],   // 148
    [false, false, false], // 149
    [false, false, false], // 150
    [true, true, false],   // 151
    [true, true, false],   // 152
    [true, true, false],   // 153
    [true, true, false],   // 154
    [true, true, false],   // 155
    [true, true, false],   // 156
    [false, false, false], // 157
    [true, true, false],   // 158
    [true, true, false],   // 159
    [true, true, false],   // 160
    [true, true, false],   // 161
    [true, true, false],   // 162
    [true, true, false],   // 163
    [true, true, false],   // 164
    [true, true, false],   // 165
    [true, true, false],   // 166
    [true, true, false],   // 167
    [true, true, false],   // 168
    [true, true, false],   // 169
    [true, true, false],   // 170
    [false, false, false], // 171
    [true, true, false],   // 172
    [true, true, false],   // 173
    [true, true, false],   // 174
    [false, false, false], // 175
    [true, true, false],   // 176
    [true, true, false],   // 177
    [true, true, false],   // 178
    [true, true, false],   // 179
    [true, true, false],   // 180
    [true, true, false],   // 181
    [true, true, false],   // 182
    [true, true, false],   // 183
    [true, true, false],   // 184
    [true, true, false],   // 185
    [true, true, false],   // 186
    [true, true, false],   // 187
    [true, true, false],   // 188
    [true, true, false],   // 189
    [true, true, false],   // 190
    [true, true, false],   // 191
    [true, true, false],   // 192
    [true, true, false],   // 193
    [true, true, false],   // 194
    [true, true, false],   // 195
    [true, true, false],   // 196
    [true, true, false],   // 197
];
