[package]
name = "rmc-render"
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
rmc-game = { path = "../rmc-game" }
rmc-ui = { path = "../rmc-ui" }
rmc-world = { path = "../rmc-world" }

[dev-dependencies]
rmc-net = { path = "../rmc-net" }
